// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/k8s-cronhpa/pkg/api/cronhpa/v1"
	scheme "github.com/k8s-cronhpa/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CronHPAsGetter has a method to return a CronHPAInterface.
// A group's client should implement this interface.
type CronHPAsGetter interface {
	CronHPAs(namespace string) CronHPAInterface
}

// CronHPAInterface has methods to work with CronHPA resources.
type CronHPAInterface interface {
	Create(ctx context.Context, cronHPA *v1.CronHPA, opts metav1.CreateOptions) (*v1.CronHPA, error)
	Update(ctx context.Context, cronHPA *v1.CronHPA, opts metav1.UpdateOptions) (*v1.CronHPA, error)
	UpdateStatus(ctx context.Context, cronHPA *v1.CronHPA, opts metav1.UpdateOptions) (*v1.CronHPA, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.CronHPA, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.CronHPAList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CronHPA, err error)
	CronHPAExpansion
}

// cronHPAs implements CronHPAInterface
type cronHPAs struct {
	client rest.Interface
	ns     string
}

// newCronHPAs returns a CronHPAs
func newCronHPAs(c *WccV1Client, namespace string) *cronHPAs {
	return &cronHPAs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cronHPA, and returns the corresponding cronHPA object, and an error if there is any.
func (c *cronHPAs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.CronHPA, err error) {
	result = &v1.CronHPA{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cronhpas").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CronHPAs that match those selectors.
func (c *cronHPAs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.CronHPAList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CronHPAList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cronhpas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cronHPAs.
func (c *cronHPAs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cronhpas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a cronHPA and creates it.  Returns the server's representation of the cronHPA, and an error, if there is any.
func (c *cronHPAs) Create(ctx context.Context, cronHPA *v1.CronHPA, opts metav1.CreateOptions) (result *v1.CronHPA, err error) {
	result = &v1.CronHPA{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cronhpas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cronHPA).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a cronHPA and updates it. Returns the server's representation of the cronHPA, and an error, if there is any.
func (c *cronHPAs) Update(ctx context.Context, cronHPA *v1.CronHPA, opts metav1.UpdateOptions) (result *v1.CronHPA, err error) {
	result = &v1.CronHPA{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cronhpas").
		Name(cronHPA.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cronHPA).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *cronHPAs) UpdateStatus(ctx context.Context, cronHPA *v1.CronHPA, opts metav1.UpdateOptions) (result *v1.CronHPA, err error) {
	result = &v1.CronHPA{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cronhpas").
		Name(cronHPA.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cronHPA).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the cronHPA and deletes it. Returns an error if one occurs.
func (c *cronHPAs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cronhpas").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cronHPAs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cronhpas").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched cronHPA.
func (c *cronHPAs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CronHPA, err error) {
	result = &v1.CronHPA{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cronhpas").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
