// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/k8s-cronhpa/pkg/client/clientset/versioned/typed/cronhpa/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeWccV1 struct {
	*testing.Fake
}

func (c *FakeWccV1) CronHPAs(namespace string) v1.CronHPAInterface {
	return &FakeCronHPAs{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeWccV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
