// Code generated by lister-gen. DO NOT EDIT.

package v1

// CronHPAListerExpansion allows custom methods to be added to
// CronHPALister.
type CronHPAListerExpansion interface{}

// CronHPANamespaceListerExpansion allows custom methods to be added to
// CronHPANamespaceLister.
type CronHPANamespaceListerExpansion interface{}
